### ISSUE TITLE
Zcash transactions are missing fields via the API

### ISSUE THREAD

**Issue by prusnak** [trezor/blockbook#120]
- missing version, versiongroupid, vjoinsplit, etc.

Example 1:
* (fields missing) https://zec1.trezor.io/api/tx/02f462a63191f8dc01aea8800d87b1ae8db4154e578677b8c33606f307843a9b
* (fields OK) https://zec1.trezor.io/tx/02f462a63191f8dc01aea8800d87b1ae8db4154e578677b8c33606f307843a9b

Oddly enough https://zec2.trezor.io/api/tx/02f462a63191f8dc01aea8800d87b1ae8db4154e578677b8c33606f307843a9b has version field, but not the other fields

Example 2:
* (fields missing) https://zec1.trezor.io/api/tx/949ab7c08c2f9ad9680af5e06176bfc1b46190789bee674a991785b831b7672d
* (fields OK) https://zec1.trezor.io/tx/949ab7c08c2f9ad9680af5e06176bfc1b46190789bee674a991785b831b7672d

Oddly enough https://zec3.trezor.io/api/tx/949ab7c08c2f9ad9680af5e06176bfc1b46190789bee674a991785b831b7672d has version field, but not the other fields (zec2 has the same error as zec1 - missing fields)

**Comment by martinboehm** [comment]
Sorry for the troubles.

This is a known and fixed bug - the tx version is not stored to tx cache (but only in case of ZCash and a few additional coins). The bug is actually kind of hard to catch because the first request (which fetches data directly from the backend) returns version but subsequent requests fetch data from tx cache and do not return version.

Unfortunately, we still run in production a Blockbook version before the fix. I will get ZCash upgraded to new Blockbook with the fix. From coins provided by us, ZCash is the only one which exhibits this problem.

**Comment by martinboehm** [comment]
In addition to that, `versiongroupid`, `vjoinsplit` will never be returned by by `/api/tx/<txid>` request. These fields are Zcash specific and are not returned by "unifying" api call `/api/tx/<txid>`. You can get those fields by a specific request `/api/tx-specific/<txid>`, which returns tx data as they are returned from backend, with all coin specific fields, however without the guarantee of some unified interface (which in case of Zcash probably does not matter).
The request `/api/tx-specific/<txid>` is not cached and will always return the version, even with currently installed Blockbook.

**Comment by prusnak** [comment]
As for the missing `version field` - we'll wait for the fix, it's not urgent.

For the rest, we'll fix the python-trezor package: https://github.com/trezor/python-trezor/pull/359

Thanks!

**Comment by martinboehm** [comment]
New version of Zcash Blockbook with the fix is released to production.
