### ISSUE TITLE
Missing tx blob

### ISSUE THREAD

**Issue by yohaaan** [trezor/blockbook#222]
**Issue:**
user is trying to send a transaction according to Blockbook API: POST /api/v1/sendtx (hex tx data in request body)

**Error message:**
responseText: {"error":"Missing tx blob"}
responseJSON: [object Object]
status: 400
statusText: Bad Request

My ajax request:
$.ajax ({
type: "POST",
url: https://cors-anywhere.herokuapp.com/https://tbtc1.trezor.io/api/v2/sendtx	
data: 'my_hexcoded_signed_transaction',
dataType: "json",
error: function(data) {
...
},
success: function(data) {
...
}	
});	

**Configuration:**

- OS: Windows 10 64-bit

**Comment by martinboehm** [comment]
@yohaaan I found the issue:

When sending POST request to the address `https://tbtc1.trezor.io/api/v2/sendtx`, Blockbook responds with a redirect to `https://tbtc1.trezor.io/api/v2/sendtx/` (see the / at the end), for which jQuery sends a new GET (instead of POST) request to the new address, without the request body. The problem is resolved when jquery ajax POST request is sent to the address `https://tbtc1.trezor.io/api/v2/sendtx/`, i.e to the address with the / at the end.
