### ISSUE TITLE
Block transactions values showing 0 & syncing delay

### ISSUE THREAD

**Issue by arons1** [trezor/blockbook#246]
I have setup blockbook and everything is working there is only one issue which I am having currently.

On the frontend when you click on a block the value is showing as 0 like this, however in the api call it shows correctly.
![image](https://user-images.githubusercontent.com/53439560/62077123-431b6d00-b241-11e9-98e5-0f2de22affff.png)

When I go to the transaction page for a specific transaction within a block it shows the value correctly as you can see here 
![image](https://user-images.githubusercontent.com/53439560/62077178-5fb7a500-b241-11e9-839d-475d5bb2e894.png) 

The same happens also on the address page like the block page.
![image](https://user-images.githubusercontent.com/53439560/62077247-92619d80-b241-11e9-944b-7a9686a6143d.png)

There is also one other issue where the last block on the backend is always ahead of the blockbook last block and takes around 15 minutes each time to catchup instead of been instant.
![image](https://user-images.githubusercontent.com/53439560/62077343-c9d04a00-b241-11e9-99c4-0d450a4fc01e.png)

**Comment by martinboehm** [comment]
The most probable reasons for you problems are:
1) zero amounts:
The problem is probably in Bitcoin Wire block parser, which is used by default. It seems not to be parsing the amounts correctly. The results from it are for performance reasons shown in block and address page. The transaction detail page queries the backend for transaction and in that case it parses amounts correctly. You can avoid the use of Bitcoin Wire block parser, if you take an approach we used for example in ZCash coin https://github.com/trezor/blockbook/blob/d450f1d31558eacccd15b9c1c720aee3ba1940ab/bchain/coins/zec/zcashrpc.go#L58. Also the PackTx/UnpackTx in the parser must be modified like in ZCash parser. After you fix it, you will have to reindex the whole DB though.

2) slow sync: it seems the ZeroMQ notifications about new blocks are not working (either the configuration is wrong or the backend does not support it). Blockbook uses a fallback mechanism, which checks every 15 minutes for new blocks. If you are not able to fix the ZeroMQ, you can change the period from 15 minutes to something smaller, like we do for example in Dogecoin - check for new blocks every 30 seconds, for mempool transactions every 2 seconds, see here https://github.com/trezor/blockbook/blob/d450f1d31558eacccd15b9c1c720aee3ba1940ab/configs/coins/dogecoin.json#L55

**Comment by arons1** [comment]
Thanks for the quick reply. 
We have solved all issues and now everything is working perfectly.
