### ISSUE TITLE
Incorrect tx order in /api/v2/xpub/

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/blockbook#372]
2 transactions sent between 2 accounts, both mined in one block.
While call /address/N show correct order /xpub/N shows opposite.

valid order:
https://tbtc1.trezor.io/api/v2/address/tb1q2ewuctpf5y3jfr34pnp9pv9tfw0hswnk7rlcws?details=txs&pageSize=2

invalid order:
https://tbtc1.trezor.io/api/v2/xpub/vpub5YsY5RC68SesZQdA9WHR1ECjuqQUJGcJDGNeuhNkLdXjhANLNF2o7FE2Sehr76eyUpeyGh2mUguD4RJ349gB8LbttqTpAzgBmaca5GKMcQL?details=txs&pageSize=2

**Comment by martinboehm** [comment]
Blockbook returns transactions for xpub or address sorted by block time descending. Multiple transactions in one block (i.e. the same time) are sorted deterministically but not necessarily in the same order as they are in the block.
This is caused by the fact that Blockbook does not index a block in the transaction order but first outputs and then inputs.
