### ISSUE TITLE
resync mempool is extremely slow when there are a lot of transactions

### ISSUE THREAD

**Issue by xiaoyuer97** [trezor/blockbook#425]
```
mempool: resync finished in 35m0.122994577s, 1227864 transactions in mempool
```

**Comment by martinboehm** [comment]
Unfortunately mempool resync is inherently slow because it must do an RPC call to the backend for each transaction. The good think is that it does only differential sync, so usually only the initial sync after restart is slow as later the transactions are coming one after another in time.

You could speedup the mempool sync a bit by increasing the parallelism using these parameters in the config file:

**Comment by martinboehm** [comment]
If the issue happens only if the service is restarted quickly, the situation could be fixed by storing the mempool to DB before shutdown and loading it after the startup. It is not really clear from the description if this is the case, however.
