### ISSUE TITLE
Error Invalid address, address collision...BYTZ blockbook

### ISSUE THREAD

**Issue by olegmitrakhovich** [trezor/blockbook#460]
I am attempting to make blockbook to work with BYTZ coin. I got it to a point where BYTZ testnet blocbook works great (http://204.92.235.57:9149) you can search by address with no issues. However, BYTZ mainnet blockbook (http://204.92.235.56:9148) I am now having issues when I try to search by address or even when I click on one of the addresses, I am getting this error: 
**"Error Invalid address, address collision"**

I am up to date with blockbook commit 07ac3c840128ddacf555cc8b4dea33f0f49d7868 and my code can be found here https://github.com/bytzcurrency/BYTZ-blockbook (master branch) ... BYTZ is a fork of PIVX 3.2

Any help would be greatly appreciated, thank you.

**Comment by martinboehm** [comment]
Hi, the error is returned from [here](https://github.com/martinboehm/btcutil/blob/d7706467ae8f226fc75667a7da185964698d2373/address.go#L198). The problem is probably in the registration of the coin, the address is detected as P2PK and P2SH at the same time. Check what networks are registered or as a "brute force" solution, you could try to call chaincfg.ResetParams() before this [line](https://github.com/bytzcurrency/BYTZ-blockbook/blob/c2e98cd739072599cce97099fb0a02215ae7bec3/bchain/coins/bytz/bytzparser.go#L76).

**Comment by olegmitrakhovich** [comment]
perfect thank you for explaining, the "chaincfg.ResetParams()" solution worked perfectly for me. @martinboehm
