### ISSUE TITLE
Unconfirmed Transations blocked

### ISSUE THREAD

**Issue by Droppix** [trezor/blockbook#480]
Hi,

I installed BTG and DOGE Testnet, and I sent 2 payments, unfortunately these 2 transactions have been blocked for several days & hours, I don't understand the problem. Do you have an idea?

Tx BTG Testnet:  https://tbtg.droppix.com/tx/7cbbfbf0f11ce5dcb1905eaa8a623b79ab64a71cf506ccf96386bcd9b5e697e8
Tx DOGE Testnet: https://tdoge.droppix.com/tx/eda88faa333695fc2e39dcea994c69bc46a910f61fcad19514b8b20e2249f3a5

Thanks

**Comment by MentalNomad** [comment]
On the BTG side, it looks like there is some sort of issue with the primary pool mining testnet (https://pool.gold/stats/tbtg) wherein some transactions don't get included; they languish.

I noticed these and mined two blocks today on a private test pool that we use when testing BTG node behavior for new code. I mined two blocks today The first, when I noticed 240 transactions in mempool, was:
https://tbtg.droppix.com/block/83044

Later, I saw your issue here, and mined this block for the other 19 backed-up messages:
https://tbtg.droppix.com/block/83058

If you can identify what these stalled TXes had in common, I'll prod the admins over at pool.gold to fix the issue.

**Comment by martinboehm** [comment]
I think this has nothing to do with Blockbook.
