### ISSUE TITLE
Building with rocksdb newer than 6.15.5 fails

### ISSUE THREAD

**Issue by 1000101** [trezor/blockbook#617]
Hi @martinboehm ! 

Building blockbook with rocksdb newer than 6.15.5 seems to [break the build](https://github.com/NixOS/nixpkgs/issues/122215#issuecomment-842395954). Is this a known issue / are there any plans on making it work with newer versions?

Thanks!

**Comment by prusnak** [comment]
Hm, it seems that `tecbot/gorocksdb` officially supports only gorocksdb 5.x for now :-/

**Comment by 1000101** [comment]
> Hm, it seems that `tecbot/gorocksdb` officially supports only rocksdb 5.x for now :-/

There seems to be a [PR](https://github.com/tecbot/gorocksdb/pull/210) addressing this, however, it seems a bit stale.

**Comment by martinboehm** [comment]
Actually, the above mentioned PR never got to us.
I am planning to do a release of Blockbook (v0.3.5) with currently used RocksDB 6.13.3 very soon (this week) and then upgrade Blockbook to the newest Go and RocksDb.
From the PR, the issue with the newer version of RocskDB seems minor anyway.

**Comment by 1000101** [comment]
> Actually, the above mentioned PR never got to us.
> I am planning to do a release of Blockbook (v0.3.5) with currently used RocksDB 6.13.3 very soon (this week) and then upgrade Blockbook to the newest Go and RocksDb.
> From the PR, the issue with the newer version of RocskDB seems minor anyway.

Great, let's track it here. Once blockbook gets upgraded to the newest go and rocksdb we can give it a go and fix https://github.com/NixOS/nixpkgs/issues/122215

**Comment by prusnak** [comment]
It seems there is a fork of gorocksdb called grocksdb https://github.com/linxGnu/grocksdb, which promises to better track RocksDB development. No idea how well battle-tested is this one, but the upstream seems active.

**Comment by martinboehm** [comment]
Thank you. There is already this commit d5cff45d8ebd8a3c1c213c3f1384a10927286d91 in the branch v0.3.6, which works with the newest RocksDB. I used a different fork and picked from it a commit which fixes only the issue with the new RocksDB but does not include any other changes from the fork to keep it simple and safe. But we can switch to the fork suggested by you if you prefer.

The branch is not yet buildable using docker build, unfortunately, because of changes in go1.16 (something related to this https://stackoverflow.com/questions/66894200/go-go-mod-file-not-found-in-current-directory-or-any-parent-directory-see-go). I did not have time yet to fix it completely.

**Comment by prusnak** [comment]
> But we can switch to the fork suggested by you if you prefer.

I don't have strong preference for either, because I have not investigated this in depth.

I just wanted to share what I found and I leave the final decision about which fork to use up to you, Martin. Thanks!

**Comment by prusnak** [comment]
> The branch is not yet buildable using docker build, unfortunately,

I've seen this earlier. Probably setting one of the following will help:

`GO111MODULE=on`
`GO111MODULE=off`
`GO111MODULE=auto`

**Comment by martinboehm** [comment]
RocksDB upgraded in v0.3.6
