### ISSUE TITLE
No cUSDT (Ethereum token) balance

### ISSUE THREAD

**Issue by wrwr** [trezor/blockbook#623]
I have some Compound USDT (cUSDT) in my ETH wallet and I can see it at https://etherscan.io/address/0x823e08493B368A23973Bf55D18C5bedc1c6925D9 but not in the Blockbook explorer: https://eth1.trezor.io/address/0x823e08493B368A23973Bf55D18C5bedc1c6925D9 - it shows I have 0 cUSDT. Is this a bug?

**Comment by martinboehm** [comment]
Thank you for the report. The problem is, that the contract is returning incorrect balance, in the form `0x0000000000000000000000000000000000000000000000000000000af9bb43ac000000000000000000000000000000000000000000000000000000000`, where correct is `0x0000000000000000000000000000000000000000000000000000000af9bb43ac` (without the trailing zeros). I made the parsing of ETH numbers more robust in this commit f0fe08a0546483b6804a61dca393f2563211ad7a, it should fix the problem.
