### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by jimmysong** [trezor/blockbook#67]
It would be really useful if the whole thing ran as a docker container. You need to install docker anyway, might as well make it so that we can build a docker image and run it anywhere.

**Comment by prusnak** [comment]
It is available from here: https://github.com/trezor/blockbook/tree/master/build/docker/bin

**Comment by martinboehm** [comment]
Actually, this is a build docker container, which produces debian packages for backend and blockbook. However, if I understand the issue correctly, the request is for a docker container, which would run the backend and blockbook. As this is not our use case - we run the software directly on server without docker, we are currently not providing this docker container. If @jimmysong creates a PR containing the runtime docker container, we will certainly merge it for others to use.

**Comment by jimmysong** [comment]
I think your users would like to have their own blockbook server to run their trezor against and not leak privacy. Do you not think this is worth doing?

**Comment by prusnak** [comment]
It is definitively worth doing. It should be very easy to adapt the builder Dockerfile and we'll give you any help you might need while doing it.

OTOH, blockbook is a Go project so the resulting binary is self-contained without any depedencies and it should be possible to run it without any problems on any distribution.

For the sake of completeness, there is another effort to docker-ize the blockbook here: https://github.com/SatoshiPortal/dockers/issues/4

**Comment by gustavonalle** [comment]
I've recently created a docker image for Blockbook and been using it with my Trezor.
It's an automated build hosted on docker hub, so if you wanna try, no need to build the image locally, just launch the container with a one-liner. More info on https://hub.docker.com/r/gustavonalle/blockbook/

Of course you can build the image locally if you want: https://github.com/gustavonalle/blockbook-docker

**Comment by martinboehm** [comment]
Thank you very much for your superb contribution!
Would it be possible to update it so that it uses our build script, i.e https://github.com/trezor/blockbook/blob/master/build/docker/bin/Dockerfile, so that the build uses the pinned `golang` and  `rocksdb` versions? It would also be forward compatible with modifications we do to our build process in the future.

**Comment by gustavonalle** [comment]
Pinning Golang and rocksdb versions is trivial. 
Regarding using the build script, as it's in fact a Dockerfile that includes another Dockerfile, I'd need to extend those images. In my case, I opted to do a manual build instead, since it's simpler and the resulting image size is considerably smaller: it is less than 500 Mb since I can execute several operations in the same Docker RUN instruction, which include the removal of temporary files.

**Comment by Jorijn** [comment]
Since I couldn't get the image of @gustavonalle running due to permission errors I decided to set up a new Dockerfile based on the building Dockerfile provided by @martinboehm. I'd like to provide a starting point for someone to clean this up and submit a pull request for this repository with matching documentation:

- Dockerfile: https://gist.github.com/Jorijn/141f49dd0c69901f28215893d5900bca
- docker-compose.yml: https://gist.github.com/Jorijn/7e1d3e7a241a98680558302a7b41586c
- Sample config: https://gist.github.com/Jorijn/c0f5d3daf6ab6d35ac25b47c2a5be331

I have this running locally against a bitcoin-core back-end. If this someone needs any additional information, feel free to reach out to me!

**Comment by gustavonalle** [comment]
Please see https://github.com/gustavonalle/blockbook-docker/issues/1#issuecomment-544133353
the issue was a misconfiguration on your side.
