### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mrpatwary** [trezor/blockbook#819]
Hello,
I used to use http://btc2.trezor.io for one of my projects.
As my project is not a huge one, I thought of not hosting my full node and wasting money and storage at the same time.
Instead, I used trezor's API to explore my incoming transactions.
It's been a few hours, and my call to btc2.trezor.io is responding with a **403 Forbidden** status code both in HTTP and HTTPS calls.
Oddly enough, the server is responding with 200 Success on my local PC whilst my Server is getting 403.
I have tried with many servers and still have the same problem. I have tried curl, wget and you name it, I tried it.

Do I now need to host the full blockbook with bitcoin full node just for keeping track of my tiny numbers of transactions?

I wonder if was that intentionally done by trezor? Or just an accident?  Please check.

Request:

`curl -I -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0" https://btc2.trezor.io/api`

Response code as follows:

`HTTP/2 403
date: Mon, 31 Oct 2022 19:52:08 GMT
content-type: text/plain; charset=UTF-8
content-length: 16
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=F2NNa2Qx8mRUkD2Rap7%2FdaePpZXTpL6e%2BlmGOXtRCdEtT1pg6lHAoDXR2PNZQVBKfyZ2Y9RqpYqk%2B8%2Bw1ydXM52KAT0T8G6sveNho%2FfKO11bdLdgtgHU8Mbo8MscUbVm"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 762eededdee778c9-CGP`

wget:

`wget https://btc2.trezor.io
--2022-10-31 19:52:33--  https://btc2.trezor.io/
Resolving btc2.trezor.io (btc2.trezor.io)... 104.20.81.175, 104.20.80.175, 172.67.33.208, ...
Connecting to btc2.trezor.io (btc2.trezor.io)|104.20.81.175|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-10-31 19:52:33 ERROR 403: Forbidden.`

Looking for solutions, or at least some suggestions.
Thank you very much for taking the time and read this.

**Comment by Dehumanizer77** [comment]
Hello,
basically this is not an issue with blockbook itself, but an instances of blockbook running on Trezor servers, so I am closing this issue.
However, to answer your question/issue, Trezor blockbook servers were never meant to be a public service, but only for use with the Trezor Suite. This is also explicitly stated at the blockbook web frontend as well - "Blockbook - blockchain indexer for Trezor wallet https://trezor.io/. Do not use for any other purpose."
Since the primary purpose of our blockbook servers is to serve Trezor Suite clients and we had problems with unrelated services using and overloading our servers, which was negatively affecting Trezor Suite users, we had to block outside services from accessing the blockbook API on our servers.
