### ISSUE TITLE
Run Blockbook with existing Node

### ISSUE THREAD

**Issue by stubbi** [trezor/blockbook#831]
Hi there,

According to the [docs](https://trezor.io/support/a/custom-backend-in-trezor-suite), Blockbook can be used to run nodes for the chains:

```
...
5. Go to blockbook/build directory and run:

> apt install ./<package name> (e.g., apt install ./backend-bitcoin_0.16.1-satoshilabs1_amd64.deb)

6. Now you can start synchronizing with the network:

> systemctl start backend-<coin>.service (e.g., systemctl start backend-bitcoin.service)
...
```

Is it also possible to configure Blockbook to use an external node potentially running on a different server instead of starting the node this way on the same machine?

Thank you very much in advance! 🙂

**Comment by Dehumanizer77** [comment]
Yes, it's possible, you need to edit /opt/coins/blockbook/bitcoin/config/blockchaincfg.json and replace 127.0.0.1 with the server of your choice (but the backend on that server needs to listen on the external IP address.
You can configure that in /opt/coins/nodes/bitcoin/bitcoin.conf (if you are running the backend package from blockbook, otherwise the location of bitcoin.conf might be different). 
The important configuration values there are `nolisten=0`, `rpcbind=0.0.0.0` and `rpcallowip=0.0.0.0/0` (alternatively you can replace rpcallowip by the ip address of the server running blockbook if you want to only allow that server).

**Comment by stubbi** [comment]
@Dehumanizer77 cool, thank you very much! 🙂
