### ISSUE TITLE
Hot restart possible?

### ISSUE THREAD

**Issue by stubbi** [trezor/blockbook#896]
Hi there,

It seems that blockbook needs to read a lot of data from disk and is slow in responding to http requests after restart. Is there some way to enforce getting the data into memory back before accepting new requests or await this?

**Comment by martinboehm** [comment]
Hi, you did not specify what coin you are using nor the size of the database nor the delay you encounter. However, Blockbook does not read a lot of data during. What takes some time is the opening of the RocksDB database, I believe mainly because it does compaction on startup. There may be  a switch which will disable compaction on startup.

**Comment by stubbi** [comment]
Right. So in that case we were running bitcoin with 64Gi of memory and it took about 45mins to restart. I am doing the investigation of RocksDB and it seems there will be some parameters to tune this. Thank you very much! :-)

**Comment by martinboehm** [comment]
That is strange. Our Bitcoin take maximum single minutes to compact and that only after initial sync when the DB is very uncompacted. Subsequent restarts take only a couple seconds.

Do you use SSD or rotational disk?
