### ISSUE TITLE
Too much disk space for bitcon

### ISSUE THREAD

**Issue by andreykanevskoi** [trezor/blockbook#911]
Hello!
I have a question about memory on the drive.
We've set up a blockbook that syncs with Bitcoin.
When I go to localhost:9130, I see two numbers:
1. "Blockbook -> Size On Disk" (approximately **380Gb**)
2. "Backend -> Size On Disk" (approximately **500Gb**)

We have a full Bitcoin node on the machine also
I have found two catalogs with the same storage volume (from localhost numbers) and that's OK.

But there is also a folder `/opt/coins/data/bitcoin/blockbook/db` that stores approximately **588Gb**. The content of the folder (a lot of .sst files) is similar to "Blockbook -> Size on Disk" source. What is this?

P.S. I thought that ".../blockbook/db" folder is a copy of "Blockbook -> Size on Disk" folder and was created by the wrong command usage. But blockbook still changes files in both of these directories.

**Comment by martinboehm** [comment]
Hi, 588Gb is kind of large for the Blockbook Bitcoin DB, but possible if you have a lot of transactions in the tx cache. The cache stores transactions fetched from the backend and only grows (there is no automated removal of transactions from the cache). You can clean the cache by stopping the Blockbook service and running
```
/opt/coins/blockbook/bitcoin/bin/ldb --db=/opt/coins/data/bitcoin/blockbook/db --hex --column_family=transactions deleterange 0x00 0xffffffffffffffffffff
```
If you do not need caching (for example because your use case accesses each transaction only once), you can run Blockbook with parameter `-notxcache`.

**Comment by andreykanevskoi** [comment]
Now it's clear, thank you!
